### ISSUE TITLE
Smart text field

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2web#129]
The `st2-form-input` directive we're using right now for `type: 'string'` fields isn't good enough when the text inside it is bigger than the field itself (which is undesirable yet not unlikely situation when we're dealing with user's existing scripts).

![2015-04-16 15 59 08](https://cloud.githubusercontent.com/assets/1357357/7178563/368969e0-e449-11e4-826c-20265eae6c99.png)

The main problem is that it is hard to scroll through the input element, especially when it is disabled (as in case of history records where user may not even realize he still can scroll this field)

New directive should automatically resize vertically depending on the length of the string. As soon as the line no longer fits in one line, it should be wrapped to the next line. Whether it should break the line by words or by characters is up for discussion.

It should inherit from ngModel to support validation and ngModelOptions out the box.

New directive is for `type: 'string'` fields only so no type conversion is necessary. On the other hand, since it is now a highly specialized field, it should support all the JSON schema properties of the [string type](http://spacetelescope.github.io/understanding-json-schema/reference/string.html) (min\maxLength, pattern and filters in the strict compliance with the RFCs provided) along with generic metadata (name, description, default, required, immutable).

There is also should be a possibility to define minimum and maximum number of rows allowed for the particular instance of the directive. This is mostly required for cases like `core.sendmail` body field when we pretty certain it would likely take more than four-five lines of text and we want to limit it to keep the form together.

From implementation standpoint, I believe it should be done with [contenteditable] element. I expect it would require a lot more effort to make UX work (keyboard support and all that stuff) than to just pick textarea, although I have a feeling textarea won't be enough for everything we want to achieve and we may spend even more time trying to hack around its limitations. Although, I might be wrong so it is up to the author to pick the right way.

**Comment by alex-shnayder** [comment]
I've implemented *st2-text-field* directive that is responsible for string fields. Since I'm new to this project, I'm not sure if I've done everything correctly.

I've chosen textarea over contenteditable for 2 main reasons:
1. As you said, it would require significant amount of effort to mimic the textarea behaviour (including angular interactions with inputs) for contenteditable.
2. There are a lot of existing libraries for elastic textareas.

For dynamic textarea height, I picked one of the libraries, revamped it and added support for min and max rows. The directives are *st2-elastic-field* and *st2-elastic-field-min/max-rows*.

The validation according to JSON schema was the easier part since length and pattern validations are already implemented in Angular. For checking the input value compliance with a given format, I've created a small bower module called *angular-value-format*. The checks are not *very* strict, but probably sufficient for the most cases. The strict validation is less performant, requires a lot of effort and is a huge task itself.

**Comment by enykeev** [comment]
@alex-shnayder thank you! I've skimmed through the code and it looks good. I'll take a closer look tomorrow and it would be great if we could talk through it after that. May be, around 14:00 NOVT if it's ok for you?

**Comment by alex-shnayder** [comment]
@enykeev Sure. How do we get in touch?

**Comment by enykeev** [comment]
Telepathically, my fellow comrade =)

Just kidding. Edward should have passed my contacts to you by now and he gave me your Skype.
