### ISSUE TITLE
I asked my browser to remember my credentials for the UI and it doesn't remember them

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2web#140]
We need dem cookies.

**Comment by enykeev** [comment]
We can't use cookies for that purpose (partially because st2auth doesn't support cookie and partially because they make very little sense in context of token-based authentication). Instead, we're storing the token in localStorage. So, you telling me you can't a) reload the page and b) open a new tab, both without the need to relogin again?

**Comment by enykeev** [comment]
@lakshmi-kannan I can't reproduce the issue. Is it still a problem for you? Could you please describe it in details?
