### ISSUE TITLE
Parameters ordering

### ISSUE THREAD

**Issue by armab** [StackStorm/st2web#154]
When showing list of parameters for specific action via CLI, the parameters are ordered first by `alphabet`, and then by `required`: 

``` sh
$ st2 run core.http -h

Action that performs an http request.

Required Parameters:
    url
        URL to the HTTP endpoint.
        Type: string

Optional Parameters:
    allow_redirects
        Set to True if POST/PUT/DELETE redirect following is allowed.
        Type: boolean
        Default: False

    auth
        Auth string to be used. This can be like 'x-auth-token=XYZ'.
        Type: string

    body
        Body to send with the request
        Type: string

    cookies
        Optional cookies to send with the request.
        Type: object

       ....
```

In Web UI control panel there is no any ordering and it's a bit confusing: 
![a13fnwj 1](https://cloud.githubusercontent.com/assets/1533818/7798943/db7304ba-0308-11e5-9680-76db9fefe70e.png)

**Comment by armab** [comment]
Apart of that, maybe it makes sense to order parameters in the same way as they appear in Metadata (yaml)?

This way integration pack developer could move to the top most frequently used parameters.

**Comment by Kami** [comment]
I think it makes sense to display the required parameters first in the UI as well. If we don't do that yet, this should almost be considered as a bug :)

Besides that, I'm not too opinionated. I could see some value in displaying the required parameters first and then using order from the metadata file.

I personally always order parameters in the required + importance order, but I know not all of the users do that and some of the metadata files are automatically generated by scripts so that's where this approach breaks.

**Comment by enykeev** [comment]
Right now, parameters in UI are only sorted by position argument (https://github.com/StackStorm/st2web/blob/master/modules/st2-auto-form/directive.js#L58).

> Apart of that, maybe it makes sense to order parameters in the same way as they appear in Metadata (yaml)?

It would be nice, but the problem is that currently, `parameters` is a yaml mapping (translated to json object during parsing) thus it doesn't have an order. To preserve an order of parameters, we would have to support another parameter definition format based on sequence of mappings. The [bitcoin.getwalletinfo](https://github.com/StackStorm/st2contrib/blob/master/packs/bitcoin/actions/getwalletinfo.yaml) for example would start to look like that:

```yaml
---
description: 'Information of the local wallet.'
enabled: true
entry_point: ''
name: getwalletinfo
parameters:
  - cmd:
        required: true
        type: string
        immutable: true
        default: 'bitcoin-cli getaccountaddress \"\"'
  - sudo:
        immutable: true
  - hosts:
        default: '{{system.btc_wallet}}'
        immutable: true
runner_type: 'remote-shell-cmd'
```

Apart from that, the only thing we can do is as you proposed, start sorting them alphabetically.

What bother me here is that we may confuse user even more. Say, we have [core.http](https://github.com/StackStorm/st2/blob/master/contrib/core/actions/http.yaml) of [http-request](https://github.com/StackStorm/st2/blob/master/st2actions/st2actions/bootstrap/runnersregistrar.py#L259-L293) and we decide to make some of parameters positional, say `method` will be first and `url` will be the second (like httpie's `http POST example.com/some`). Mind that `url` is required, while `method` isn't. How should we sort it then?

Ignore required, but keep position:
- method
- url *
- cookie
- ...

Prioritize required before position rendering the latter useless in this case:
- url *
- method
- cookie

Either way, alphabetical sorting will end up with the smallest priority so in a presence of positional arguments, it might start sorting parameters alphabetically somewhere in the middle of the form.

So, as you see, there is no obvious approach to sorting. I wonder whether instead we could make things better by reducing the number of parameters shown, say, by adding binary attribute `optional` and hiding some of them under the cut.

**Comment by manasdk** [comment]
Will indulge with my 2c :)

* positional is only for those actions which require the command to be constructed with a certain positional order. It is not terribly useful in our UI/CLI since we only employ named params. Implicitly, there is no special meaning to positional that we should associate for the users of our system.
* `required` as Kami pointed should have highest precedence . Then everything is alphabetic within the required group and the optional group.

On array as parameters -
* The trick is that array will not prevent duplicate names and we will have to enforce or somehow come up with weird semantics around duplicate param names. (argparse does this very awkwardly). So yeah relying on order being preserved from YAML -> JSON is kinda pointless.

**Comment by armab** [comment]
> `required` as Kami pointed should have highest precedence . Then everything is `alphabetic` within the required group and the optional group.

Yeah,
looks like CLI `st2 run core.http -h` works in this way.

**Comment by Kami** [comment]
> required as Kami pointed should have highest precedence . Then everything is alphabetic within the required group and the optional group.

+1 on that as well.

**Comment by emptywee** [comment]
Maybe just add an optional `webui_order` param for starters? It would let users order their params whatever way they want.

**Comment by emptywee** [comment]
Something like that:
```  parameters:
    skip_notify:
      default: []
      type: "array"
      description: "List of tasks to skip notifications for."
      webui_order: 50
    task:
      type: "string"
      description: "The name of the task to run for reverse workflow."
      webui_order: 10
    group:
      default: "group1"
      type: "string"
      description: "Group name to place hosts under in ansible inventory (to acquire group vars)"
      webui_order: 5
    workflow:
      type: "string"
      description: "The name of the workflow to run if the entry_point is a workbook of many workflows. The name should be in the format \"<pack_name>.<action_name>.<workflow_name>\". If entry point is a workflow or a workbook with a single workflow, the runner will identify the workflow automatically."
      webui_order: 25
    files_to_copy:
      default:
        - "/etc/sudoers"
      type: "array"
      description: "Files to copy over from the reference server (if set)"
      webui_order: 30

```

**Comment by Kami** [comment]
> Maybe just add an optional webui_order param for starters? It would let users order their params whatever way they want.

I'm personally not too big of a fan of this approach.

Metadata file should be generic and consumer agnostic. Keep in mind that the WebUI is just one of many possible API consumers so we need to make sure we keep metadata generic and not biased to a single consumer.

I'm fine with a solution which is consumer / medium agnostic or some how implementing this feature as part of WebUI (similar as we do in the flow for task coordinates).

**Comment by codyaray** [comment]
+1 This issue is starting to come up for us as I try to get buy-in from non-technical users.

**Comment by pietervogelaar** [comment]
+1 When will a solution be implemented? The issue is already one year old.
