### ISSUE TITLE
Action/Details/History doesn't show full workflow

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2web#180]
Only last few actions are shown, and NO indication given that there are more actions. 
The fix is to show ALL tasks in the workflow. 

This is what is shown: 
![image](https://cloud.githubusercontent.com/assets/1294734/9337951/13a4bad8-4597-11e5-9f93-342414427452.png)

And this is the full history: 
![image](https://cloud.githubusercontent.com/assets/1294734/9337986/3485d4f8-4597-11e5-935e-cef0418d99ca.png)

**Comment by emedvedev** [comment]
@enykeev said it's intended behavior and there's a filter to only show the last five. Can you confirm we should remove the filter? This could display a very long list in some cases.

**Comment by dzimine** [comment]
We only show last five of top-level executions. When it expands, we don' want to limit the expanded sub-execution.

**Comment by emedvedev** [comment]
Created a PR.

Another—but unrelated—problem is, when I try to get a list of executions for an action I see a message saying "No history records for this action". Turns out it's actually a placeholder for a request taking **35 seconds** to complete, because it's pulling 2.6 megabytes of data. Then the execution list finally appears. 

So, not only "No history records" is a wrong message because there are records and they're just loading, but getting a 2.6 megabytes request to show a short list is something that shouldn't happen to begin with.

Should I create an issue somewhere? I could take this up myself but I feel like someone with more intimate knowledge of st2api would probably fix this ten times faster than me.

![screenshot 2015-08-20 17 39 24](https://cloud.githubusercontent.com/assets/145218/9382955/7a0707ae-475e-11e5-8a89-dedb1295ed90.png)
