### ISSUE TITLE
ENV field stays highlighted red even after key value pair gets typed in

### ISSUE THREAD

**Issue by rtsai123** [StackStorm/st2web#280]
hi I am trying to run the jenkins_build_job action from the ui. Every time I try and add env variables the field always stays red and never allows me to select the RUN button. If I run the command from the CLI it works.
st2 --version
st2 ('1.2.0.8',) 

![screen shot 2016-02-02 at 2 24 26 pm](https://cloud.githubusercontent.com/assets/1918845/12766682/bb5e603e-c9b9-11e5-92b4-3770b579bcb7.png)

**Comment by enykeev** [comment]
Web UI currently only support JSON notation for objects. You can try defining it as `{"build": true, "prod": true}`.

The description is misleading because it was initially written for cli client and did not account for specifics of web client. I will leave this issue open as a reminder to eliminate the difference one way or the other.

**Comment by rtsai123** [comment]
Ok that makes sense.  Thanks for info!
