### ISSUE TITLE
Support for timestamp display timezones

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2web#292]
st2web part of this change - https://github.com/StackStorm/st2/issues/2532

**Comment by stevemuskiewicz** [comment]
@emedvedev: @Kami told me in Slack to ping you about possibly fixing this one??

**Comment by emedvedev** [comment]
Yes, it would be either me or @enykeev, but I can't give an estimate just yet. Don't worry, we'll get it done. :)

**Comment by stevemuskiewicz** [comment]
cool thanks!

**Comment by codyaray** [comment]
+1 from someone else on my team too! :)

**Comment by ckamps** [comment]
When this enhancement is made, will the ability to set a default web UI timezone be supported so that the majority of our users don't have to make a change to see events aligned to our global enterprise-wide single timezone standard?

Better yet, a means to force both the web UI and CLI to act on the same default display timezone setting?  Especially since we'd like to avoid needing to customize CLI client configs across the board vs manage the default display timezone setting in one place.

**Comment by stevemuskiewicz** [comment]
So I can see this works in the cli by setting `timezone` in `~/.st2/config`, but how to we expose this configuration to the ui so that it also uses the same timezone setting?

Would be nice to be able to just set in `/etc/st2/st2.conf` and have it apply to everything (UI and CLI)

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1494603136434743

**Comment by ramgolla** [comment]
+1 for both CLI and UI support for local timezone.  Multiple automation suite customers are asking for this!
