### ISSUE TITLE
High Resource Utilization

### ISSUE THREAD

**Issue by bigmstone** [StackStorm/st2web#335]
It would appear when a significant number of actions are displayed in history, high CPU usage is seen. On the order of 50-60% of an i7 mobile CPU. This should be easy to recreate by browsing to st2-build's history page.

![image](https://cloud.githubusercontent.com/assets/4266996/20330233/f9f6578a-ab62-11e6-80e4-6e004a0d396a.png)

![image](https://cloud.githubusercontent.com/assets/4266996/20330261/23cb8080-ab63-11e6-8daf-e45a2ddb6095.png)

Can someone see if this can be reproduced on, say, a Mac? If it's isolated to Linux then I'm fine with it bing ignored. I'll try on other browsers too.

**Comment by enykeev** [comment]
This spikes most likely related to browser trying to highlight big chunks of code. We're fighting this problem one way or the other since the first days, but have only managed to make it not to block the browser itself.

On my i7 mac, cpu utilization rarely spikes higher than 30% of a single core in both chrome and firefox. The UI still seem sluggish, but st2-build doesn't run the latest version of st2web either.
