### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by absolutejam** [StackStorm/st2web#337]
Hey guys,

Apologies for dropping an issue on you, but is there currently a container for this? Seems to be missing from the rest of the containers?

Regards,
James.

**Comment by enykeev** [comment]
Web UI doesn't need a container because it doesn't have an executable to run. It's just a static web content you distribute with web server of choice. In our reference deployment, we serve it from the same nginx instance that handles ssl termination and routing, but it might look some other way in your environment.
