### ISSUE TITLE
Switching views too fast leads to error messages

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2web#401]
When you change view too fast, i.e.:
- click "actions", then immediately
- click "History"

this leads to an error box shown in the down left corner, with a message like:

```
Failed to update list
$scope.$root is null
```

and another one

```
Failed to fetch action
$scope.$root is null
```

**Comment by LindsayHill** [comment]
I have seen some similar behavior too. Have not done extensive testing of it though. Needs some more testing to check browsers/versions/conditions, to make sure it's repeatable, and to get the JS console logs.

**Comment by enykeev** [comment]
@vincent-legoll I feel a need to apologize, it might seem like we're ignoring the issues you're raising. In fact, the project currently undergoes a massive transition and I'm hoping we can fix them all by the next minor release (2.5). Thank you and please keep up the good work!

**Comment by vincent-legoll** [comment]
@enykeev: OK, no problem, but why closing the issue before it has been tested as being fixed ?

I can wait for a new version, and I'll try it to see if it has been fixed, so why loosing the issue as a tracking tool ?

At least, I, may forgot to test it without something to remind me...

**Comment by enykeev** [comment]
@vincent-legoll the issue was closed automatically when I merged the PR linked to it with `resolves` keyword. It is still being tracked and could be reopened if the problem is not fixed.

If you want to test it yourself, you can spin a clean vm and install an unstable staging version of st2 with oneliner

```
curl -sSL https://stackstorm.com/packages/install.sh | bash -s -- --user=st2admin --password='Ch@ngeMe' --unstable --staging
```

Alternatively, you can download the st2web package from our [packagecloud repo](https://packagecloud.io/StackStorm/staging-unstable) or from [CircleCI artifacts](https://circleci.com/gh/StackStorm/st2web/418#artifacts/containers/0) for the build.
