### ISSUE TITLE
GULP ERROR IS THROWN WHEN EXECUTE COMMAND GULP

### ISSUE THREAD

**Issue by SURAJTHEGREAT** [StackStorm/st2web#494]
/home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /home/ubuntu/.nvm/versions/node/v8.4.0/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by christopherjbaker** [comment]
This project is using gulp 4, which is not compatible with gulp 3, which is what you have installed globally. After you install the dependencies, you can use our npm scripts to run gulp. instead of running it directly, which will run the local install. `npm run develop` is equivalent to `gulp`. there is also `npm run build` and `npm run test`.

If you are curious, here is [a blog post](https://codeburst.io/maybe-dont-globally-install-that-node-js-package-f1ea20f94a00) that discusses the specifics of this setup and the reasoning behind it.
